=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ApplicationBehavior/ApplicationBehaviors.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- Schema used to specify how to handle specific application windows, part of the virtual desktop manager of the ABC toolkit. -->
<xs:schema
  id="ApplicationBehaviors"
  targetNamespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xmlns="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:ab="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Custom GUID type since it is not available in XSD definition. -->
  <xs:simpleType name="Guid">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        The representation of a GUID, generally the id of an element.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="\{[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ProcessVersion">
    <xs:annotation>
      <xs:documentation>Defines a process version number (major.minor.build.revision). Only major is mandatory.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="(\d+\.){0,3}(\d+)" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Type which can uniquely identify one particular window of a process. -->
  <xs:complexType name="Window">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Uniquely identifies a window, hosted by a process.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="ClassName" type="xs:string" use="required" />
    <xs:attribute name="Title" type="xs:string" />
    <xs:attribute name="Visible" default="Both">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="True" />
          <xs:enumeration value="False" />
          <xs:enumeration value="Both" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <!-- Type which lists a set of windows. -->
  <xs:complexType name="WindowList">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        A list of windows.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Window" type="Window" />
    </xs:sequence>
  </xs:complexType>

  <!-- Type which determines the windows which should be considered during a window operation. -->
  <xs:simpleType name="ConsiderWindows">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Determines the windows which should be considered during window operations.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="AllWindows" />
      <xs:enumeration value="CurrentDesktopWindowsOnly" />
      <xs:enumeration value="AllDesktopWindows" />
    </xs:restriction>
  </xs:simpleType>


  <!-- Specifies for an application, how its process windows should be handled. -->
  <xs:element name="ApplicationBehaviors">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Specifies for an application, how its process windows should be handled.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CommonIgnoreWindows" type="WindowList" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              A list of windows which need to be ignored, independent of the process that hosts them.
            </xs:documentation>
          </xs:annotation>
        </xs:element>

        <xs:sequence minOccurs="1" maxOccurs="unbounded">
          <xs:element name="Process">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                Specifies for one process, how to handle its windows.
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>

              <xs:sequence>
                <!-- A list of windows which should be ignored entirely by the Virtual Desktop Manager. -->
                <xs:element name="IgnoreWindows" minOccurs="0" maxOccurs="1">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">
                      A list of windows which should be ignored entirely by the Virtual Desktop Manager.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:complexContent>
                      <xs:extension base="WindowList">
                        <xs:attribute name="Mode" default="NoneExcept">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="AllExcept" />
                              <xs:enumeration value="NoneExcept" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:extension>
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>

                <!-- Describes which windows should be cut when a window of this process is cut. -->
                <xs:element name="HideBehavior" minOccurs="0" maxOccurs="1">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">
                      Describes which windows should be cut when a window of this process is cut.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                      <xs:choice>
                        <!-- Default window selections. -->
                        <xs:element name="Default">
                          <xs:complexType>
                            <xs:attribute name="Hide" use="required">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="SelectedWindow" />
                                  <xs:enumeration value="AllProcessWindows" />
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="ConsiderWindows" type="ConsiderWindows" default="CurrentDesktopWindowsOnly" />
                          </xs:complexType>
                        </xs:element>

                        <!-- Opt-in window selection. -->
                        <xs:element name="Include">
                          <xs:complexType>
                            <xs:complexContent>
                              <xs:extension base="WindowList">
                                <xs:attribute name="ConsiderWindows" type="ConsiderWindows" default="CurrentDesktopWindowsOnly" />
                              </xs:extension>
                            </xs:complexContent>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>

              <xs:attribute name="Name" type="xs:string" use="required" />
              <xs:attribute name="CompanyName" type="xs:string" use="required"/>
              <xs:attribute name="Version" type="ProcessVersion">
                <xs:annotation>
                  <xs:documentation>
                    The version to which this configuration applies. All versions are targeted by default.
                    Version numbers do not need to be complete; 'underlying' versions are also targeted.
                  </xs:documentation>
                </xs:annotation>
              </xs:attribute>

            </xs:complexType>

          </xs:element>
        </xs:sequence>
      </xs:sequence>

      <xs:attribute name="Guid" type="Guid" use="required">
        <xs:annotation>
          <xs:documentation>Uniquely describes this configuration for the virtual desktop manager.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
    </xs:complexType>

    <xs:unique name="UniqueProcess">
      <xs:selector xpath="ab:Process" />
      <xs:field xpath="@Name" />
      <xs:field xpath="@CompanyName" />
      <xs:field xpath="@Version" />
    </xs:unique>

  </xs:element>

</xs:schema>

=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ApplicationBehavior/windows.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- Default Windows installation (originally created for Windows 7, but since stuff for 8 and 10 got added). -->
<ApplicationBehaviors
  xmlns="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatheco.de/abc/workspaces/windows ApplicationBehaviors.xsd"
  Guid="{F13D1F88-05E6-4DDA-B606-9B9BE53E4334}">

  <!-- Common windows which need to be ignored in all applications. -->
  <CommonIgnoreWindows>
    <!-- Shadow of menus and tooltips. -->
    <Window ClassName="SysShadow" />
    <!-- Tooltips. -->
    <Window ClassName="tooltips_class32" />

    <!-- TODO: What are these exactly? -->
    <Window ClassName="GDI+ Hook Window Class" />
    <Window ClassName="IME" />
    <Window ClassName="MSCTFIME UI" />
    <Window ClassName="WorkerW" />
    <!-- TODO: How unique are these class names? Do we need wildcard support? -->
    <Window ClassName=".NET-BroadcastEventWindow.4.0.0.0.5c39d4.0" />
    <Window ClassName="WindowsForms10.Window.0.app.0.5c39d4_r20_ad1" />
  </CommonIgnoreWindows>

  <!-- Explorer. -->
  <Process Name="explorer" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <!-- Start button. -->
      <Window ClassName="Button" />
      <!-- Start bar. -->
      <Window ClassName="Shell_TrayWnd" />
      <!-- Start menu. -->
      <Window ClassName="DV2ControlHost" />
      <!-- Start menu user picture. -->
      <Window ClassName="Desktop User Picture" />
      <!-- Desktop icons. -->
      <Window ClassName="Progman" />
      <!-- View available networks dialog and tooltip. -->
      <Window ClassName="NativeHWNDHost" />
      <Window ClassName="VANUITooltip" />

      <!-- TODO: Get more information on these windows, what they are, and whether they should really be ignored. -->
      <Window ClassName="_SearchEditBoxFakeWindow" />
      <Window ClassName="AUTHUI.DLL: Shutdown Choices Message Window" />
      <Window ClassName="Auto-Suggest Dropdown" />
      <Window ClassName="ComboLBox" />
      <Window ClassName="Media Center SSO" />
      <Window ClassName="PrintCacheLocalConnectionListenerHiddenWindow" />
      <Window ClassName="PrintCacheListenerWindow_19A79E3F-0006-4175-AACD-6F5C69CC0D23" />
      <Window ClassName="TaskSwitcherWnd" />
    </IgnoreWindows>
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>

  <!-- This process triggered a window once a Windows Phone was plugged in, used to indicate the phone is connected, and to open up the related software. -->
  <!-- Noticed when plugging in a Nokia Lumia 720. -->
  <!-- TODO: Should some of its windows be handled differently? -->
  <Process Name="Dxpserver" CompanyName="Microsoft Corporation">
    <IgnoreWindows Mode="AllExcept" />
  </Process>

  <!-- Windows Ink Services Platform Tablet Input Subsystem. -->
  <!-- TODO: Verify what these windows do exactly, and whether they can be ignored. -->
  <Process Name="wisptis" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <Window ClassName="wisptis_feedback_window" />
    </IgnoreWindows>
  </Process>

  <!-- Taskhost is used as the host for all DLL based services that are run. -->
  <Process Name="taskhost" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <!-- TODO: Showing this window doesn't make it show up, but where is this coming from? -->
      <Window ClassName="COMTASKSWINDOWCLASS" />
    </IgnoreWindows>
  </Process>

  <!-- Window 10 weather metro app. -->
  <Process Name="Microsoft.Msn.Weather" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <Window ClassName="Windows.UI.Core.CoreWindow" />
    </IgnoreWindows>
  </Process>

  <!-- Window 10 e-mail metro app. -->
  <Process Name="HxMail" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <Window ClassName="Windows.UI.Core.CoreWindow" />
    </IgnoreWindows>
  </Process>

  <!-- Default built-in windows photo viewer. -->
  <Process Name="dllhost" CompanyName="Microsoft Corporation">
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>
  
</ApplicationBehaviors>

=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ApplicationBehavior/asus.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- Preinstalled applications on ASUS laptops. -->
<ApplicationBehaviors
  xmlns="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatheco.de/abc/workspaces/windows ApplicationBehaviors.xsd"
  Guid="{16BFEB43-5C67-48C8-896C-3217593E7B29}">

  <!-- Asus function key visualizations. -->
  <Process Name="ATKOSD2" CompanyName="ASUSTek Computer Inc.">
    <IgnoreWindows>
      <Window ClassName="CNewOsd" />
    </IgnoreWindows>
  </Process>

  <!-- Asus Splendid Video Enhancement Technology. Window is never shown. -->
  <Process Name="ACMON" CompanyName="ASUS">
    <IgnoreWindows>
      <Window ClassName="ACMON" />
    </IgnoreWindows>
  </Process>

  <!-- Asus touchpad driver. -->
  <Process Name="ETDCtrl" CompanyName="ELAN Microelectronics">
    <IgnoreWindows>
      <Window ClassName="#32770" />
    </IgnoreWindows>
  </Process>
  <Process Name="ETDCtrlHelper" CompanyName="ELAN Microelectronics">
    <IgnoreWindows>
      <Window ClassName="#32770" />
    </IgnoreWindows>
  </Process>

</ApplicationBehaviors>

=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ApplicationBehavior/ms_office.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- Microsoft Office (originally created for 2010). -->
<ApplicationBehaviors
  xmlns="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatheco.de/abc/workspaces/windows ApplicationBehaviors.xsd"
  Guid="{5E35C3F5-E5E7-4953-AE5D-4D9729875D55}">

  <!-- Word. -->
  <Process Name="WINWORD" CompanyName="Microsoft Corporation">
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>

  <!-- OneNote. -->
  <Process Name="ONENOTE" CompanyName="Microsoft Corporation">
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>

  <!-- PowerPoint. -->
  <Process Name="POWERPNT" CompanyName="Microsoft Corporation">
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>

  <!-- InfoPath. -->
  <Process Name="INFOPATH" CompanyName="Microsoft Corporation">
    <HideBehavior>
      <Default Hide="SelectedWindow" />
    </HideBehavior>
  </Process>

</ApplicationBehaviors>

=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ApplicationBehavior/chrome.xml
<?xml version="1.0" encoding="utf-8" ?>

<!-- Chrome web browser. -->
<ApplicationBehaviors
  xmlns="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatheco.de/abc/workspaces/windows ApplicationBehaviors.xsd"
  Guid="{E06E2AEA-5C54-411D-950D-2EA952262BE4}">
  
  <Process Name="chrome" CompanyName="Google Inc.">
    <IgnoreWindows>
      <!-- TODO: What is this? -->
      <Window ClassName="Messaging" />
      <Window ClassName="Base_PowerMessageWindow" />
      <Window ClassName="SWFlash_PlaceholderX" />
      <Window ClassName="CSpNotify Notify Window" />
    </IgnoreWindows>
    <HideBehavior>
      <Default Hide="SelectedWindow" />
      <!-- Also take into account the currently visible status bar. -->
      <Include ConsiderWindows="AllWindows">
        <!-- Apparently both classes are used for the main windows, as well as status bars. However, status bars don't have a title set. -->
        <Window ClassName="Chrome_WidgetWin_0" Visible="True" Title="" />
        <Window ClassName="Chrome_WidgetWin_1" Visible="True" Title="" />
      </Include>
    </HideBehavior>
  </Process>

</ApplicationBehaviors>
