=== StevenHouben/ABC/ABC/ABC/Workspaces/Windows/Settings/ProcessBehavior/ProcessBehaviors.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema
  id="ProcessBehaviors"
  targetNamespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xmlns="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors"
  xmlns:pb="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <!-- Type which can uniquely identify one particular window of a process. -->
  <xs:complexType name="Window">
    <xs:attribute name="ClassName" type="xs:string" />
    <xs:attribute name="Title" type="xs:string" />
    <xs:attribute name="Visible" default="Both">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="True" />
          <xs:enumeration value="False" />
          <xs:enumeration value="Both" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <!-- Type which lists a set of windows. -->
  <xs:complexType name="WindowList">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Window" type="Window" />
    </xs:sequence>
  </xs:complexType>

  <!-- Type which determines the windows which should be considered during a window operation. -->
  <xs:simpleType name="ConsiderWindows">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AllWindows" />
      <xs:enumeration value="CurrentDesktopWindowsOnly" />
      <xs:enumeration value="AllDesktopWindows" />
    </xs:restriction>
  </xs:simpleType>


  <!-- List of processes with desired behaviors on how the Virtual Desktop Manager should handle its containing windows. -->
  <xs:element name="ProcessBehaviors">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CommonIgnoreWindows" type="WindowList" minOccurs="0" maxOccurs="1" />

        <xs:sequence minOccurs="1" maxOccurs="unbounded">

          <xs:element name="Process">
            <xs:complexType>

              <xs:sequence>
                <!-- A list of windows which should be ignored entirely by the Virtual Desktop Manager. -->
                <xs:element name="IgnoreWindows" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                    <xs:complexContent>
                      <xs:extension base="WindowList">
                        <xs:attribute name="Mode" default="NoneExcept">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="AllExcept" />
                              <xs:enumeration value="NoneExcept" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:extension>
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>

                <!-- Describes which windows should be cut when a window of this process is cut. -->
                <xs:element name="HideBehavior" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                      <xs:choice>
                        <!-- Default window selections. -->
                        <xs:element name="Default">
                          <xs:complexType>
                            <xs:attribute name="Hide" use="required">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="SelectedWindow" />
                                  <xs:enumeration value="AllProcessWindows" />
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="ConsiderWindows" type="ConsiderWindows"
                                          default="CurrentDesktopWindowsOnly" />
                          </xs:complexType>
                        </xs:element>

                        <!-- Opt-in window selection. -->
                        <xs:element name="Include">
                          <xs:complexType>
                            <xs:complexContent>
                              <xs:extension base="WindowList">
                                <xs:attribute name="ConsiderWindows" type="ConsiderWindows"
                                              default="CurrentDesktopWindowsOnly" />
                              </xs:extension>
                            </xs:complexContent>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>

              <xs:attribute name="Name" type="xs:string" use="required" />
              <xs:attribute name="CompanyName" type="xs:string" />
              <xs:attribute name="Version" type="xs:string" />
              <xs:attribute name="Author" type="xs:string" />

            </xs:complexType>

          </xs:element>

        </xs:sequence>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="UniqueProcess">
      <xs:selector xpath="pb:Process" />
      <xs:field xpath="@Name" />
      <xs:field xpath="@CompanyName" />
      <xs:field xpath="@Version" />
    </xs:unique>

    <xs:unique name="UniqueNameVendor">
      <xs:selector xpath="pb:Process" />
      <xs:field xpath="@Name" />
      <xs:field xpath="@CompanyName" />
    </xs:unique>

  </xs:element>

</xs:schema>

=== StevenHouben/ABC/ABC/ABC.Windows/Desktop/Settings/ProcessBehavior/default_settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<ProcessBehaviors
  xmlns="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatodo.at/whathecode/vdm-api ProcessBehaviors.xsd">

  <!-- Common windows which need to be ignored in all applications. -->
  <CommonIgnoreWindows>
    <!-- Shadow of menus and tooltips. -->
    <Window ClassName="SysShadow" />
    <!-- Tooltips. -->
    <Window ClassName="tooltips_class32" />
  </CommonIgnoreWindows>


  <!-- Default windows 7. -->
  <Process Name="explorer" CompanyName="Microsoft Corporation">
    <IgnoreWindows>
      <!-- Start button. -->
      <Window ClassName="Button" />
      <!-- Start bar. -->
      <Window ClassName="Shell_TrayWnd" />
      <!-- Start menu. -->
      <Window ClassName="DV2ControlHost" />
      <!-- Start menu user picture. -->
      <Window ClassName="Desktop User Picture" />
      <!-- Desktop icons. -->
      <Window ClassName="Progman" />

      <!-- TODO: Get more information on these windows, what they are, and whether they should really be ignored. -->
      <Window ClassName="_SearchEditBoxFakeWindow" />
      <Window ClassName="AUTHUI.DLL: Shutdown Choices Message Window" />
      <Window ClassName="IME" />
      <Window ClassName="Media Center SSO" />
      <Window ClassName="MSCTFIME UI" />
      <Window ClassName="TaskSwitcherWnd" />
      <Window ClassName="WorkerW" />
    </IgnoreWindows>
  </Process>

  <!-- Pen input. -->
  <Process Name="wisptis" CompanyName="">
    <IgnoreWindows>
      <Window ClassName="wisptis_feedback_window" />
    </IgnoreWindows>
  </Process>

  <!-- Chrome. -->
  <Process Name="chrome" CompanyName="Google Inc.">
    <IgnoreWindows>
      <!-- Status bar. -->
      <Window ClassName="Chrome_WidgetWin_0" />
    </IgnoreWindows>
    <HideBehavior>
      <Default Hide="SelectedWindow" />
      <!-- Also take into account the currently visible status bar. -->
      <Include ConsiderWindows="AllWindows">
        <Window ClassName="Chrome_WidgetWin_0" Visible="True" />
      </Include>
    </HideBehavior>
  </Process>

  <!-- Asus function key visualizations. -->
  <Process Name="ATKOSD2" CompanyName="ASUSTek Computer Inc.">
    <IgnoreWindows>
      <Window ClassName="CNewOsd" />
    </IgnoreWindows>
  </Process>

</ProcessBehaviors>
