=== StevenHouben/ABC/ABC/ABC.PluginManager/SupportedApplications.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema
  id="SupportedApplications"
  targetNamespace="http://whatodo.at/abc/abc-api/SupportedApplications"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xmlns="http://whatodo.at/abc/abc-api/SupportedApplications"
  xmlns:pb="http://whatodo.at/abc/abc-api/SupportedApplications"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Custom GUID type since it is not available in XSD definition. -->
  <xs:simpleType name="guid">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        The representation of a GUID, generally the id of an element.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="\{[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- List of all supported applications. -->
  <xs:element name="SupportedApplications">
   
    <xs:complexType>
      <xs:sequence>
        
        <xs:element minOccurs="1" maxOccurs="unbounded" name="Application">
          <xs:complexType>
            <xs:sequence>

              <!-- List of all executables that are targeted by an applications. -->
              <xs:element minOccurs="1" maxOccurs="1" name="TargetExecutables">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs ="unbounded" name="Executable">
                      <xs:complexType>
                        <xs:attribute name="Guid" type="guid" use="required" />
                        <xs:attribute name="ProcessName" type="xs:string" use="required" />
                        <xs:attribute name="CompanyName" type="xs:string" use="required" />
                        <xs:attribute name="Version" type="xs:decimal" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <!-- List of Plug-ins for an applications. -->
              <xs:element name="Plugins" minOccurs="1" maxOccurs="1">
                
                <xs:complexType>
                  <xs:sequence>
                    
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="Plugin">
                      <xs:complexType>
                        <xs:sequence>

                          <!-- List of ABC plug-ins that are forming one complete plug-in. -->
                          <xs:element name="AbcPlugins" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                
                                <xs:element minOccurs="1" maxOccurs="unbounded" name="AbcPlugin">
                                  <xs:complexType>
                                    <xs:attribute name="Guid" type="guid" use="required" />
                                    <xs:attribute name="TargetVersion" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                                
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          
                        </xs:sequence>
                        <xs:attribute name="Version" type="xs:decimal" use="required" />
                        <xs:attribute name="Author" type="xs:string" use="required" />
                        <xs:attribute name="icon" type="xs:string" />
                        <xs:attribute name="Description" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
            <xs:attribute name="Guid" type="guid" use="required" />
            <xs:attribute name="Name" type="xs:string" use="required" />
            <xs:attribute name="Author" type="xs:string" use="required" />
            <xs:attribute name="Icon" type="xs:string" />
          </xs:complexType>
          
        </xs:element>
      </xs:sequence>
      
    </xs:complexType>
  </xs:element>
</xs:schema>

=== StevenHouben/ABC/ABC/ABC.PluginManager/SupportedApplications.xml
<?xml version="1.0" encoding="utf-8" ?>

<SupportedApplications
  xmlns="http://whatodo.at/abc/abc-api/SupportedApplications"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://whatodo.at/abc/abc-api SupportedApplications.xsd">

  <Application Author ="Microsoft Corporation" Guid="{8E3C1F5A-6970-49A2-8D41-5224169A0804}" Name="Windows 7">
    <TargetExecutables>
      <Executable Guid="{FC7783D8-988B-4C3B-AD24-6CA241568199}" ProcessName="explorer" CompanyName="Microsoft Corporation" />
      <Executable Guid="{ED7A078D-DE93-4EC4-AB7D-A5B7CBDDFE55}" ProcessName="Dxpserver" CompanyName="Microsoft Corporation"/>
      <Executable Guid="{E32105B4-0506-43C7-8F48-777CDAA67183}" ProcessName="wisptis" CompanyName="Microsoft Corporation"/>
      <Executable Guid="{F0A626EB-AC17-4157-8363-0E965C657BB7}" ProcessName="taskhost" CompanyName="Microsoft Corporation"/>
    </TargetExecutables>
    <Plugins>
      <Plugin Version="1.0" Author="TestAuthor" icon="TestIcon.ico" Description="Provides some functionality 1">
        <AbcPlugins>
          <AbcPlugin Guid="{AC0385EB-66BA-49F5-B276-ECC6246D621C}" TargetVersion="1.0"/>
          <AbcPlugin Guid="{C0585332-8F2E-448B-9931-AF86399C020B}" TargetVersion="2.0"/>
        </AbcPlugins>
      </Plugin>
    </Plugins>
  </Application>

</SupportedApplications>
